##################
# ---- Jump ---- #
##################

# Protection settings
plates:
  # Weather or not to delete pressure plates when a point location is changed
  auto delete: yes
  # Disallow to break plates
  # Note: Enabling this feature may impact performances if a lot of break events occur in the same world of jumps
  protect: yes
  # Each checkpoint, start, end points need to have a pressure plate to be used by the plugin
  # materials can be (case insensitive): gold, iron, stone, or wood
  materials:
    start: gold
    end: gold
    checkpoint: iron

# Game settings
game:
  # Time wait until enable players to reset their chrono (millis)
  reset time: 1000
  # Max fall distance before teleport the player to its last checkpoint (-1 to disable)
  max fall distance: 5
  # Reset enchantments when a player begin a jump
  reset enchants: yes
  # color of the bossbar (possible values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html)
  bossbar: green
  # Allowed command while in jump, other commands performed by player will cause it to leave the jump
  allowed commands:
    # Jump plugin
    - jump
    - j # jump alias (don't forget it :) )
    - checkpoint
    - cp
    # Essentials example
    - msg
    - r

# Editor settings
editor:
  # Put editor in creative mode to be able to break plates, use fly and add blocks
  # Notes: - Player will still need jump.admin.editorinteraction to break and place blocks
  #        - Players without the permission here above cannot add item to there inventory through creative panel
  creative: yes

# Gui settings
best scores:
  # Score count stored in files (does not change scores shown to players)
  per jump: 10
  # Score count show in the book
  per player: 5

# Parkour settings
parkour:
  # Width of description in the jump list
  description wrap length: 50 # characters
  # Default item used as icon for the jump
  default icon: SLIME_BLOCK

# Storages properties
storage:
  # Implementation to use, either:
  #  - yaml (fallback if not recognized)
  #  - mysql
  #  - ... (more coming soon)
  implementation: "yml"
  # Server properties if the implementation is a remote database
  remote:
    # IP of the server
    host: "localhost"
    # Port of the server, default are
    #   MySQL: 3306
    port: 3306
    # Name of the database
    name: "database"
    # User to use again the database
    user: "root"
    # User's password
    pass: ""
